CREATE TABLE WEB_USERS (
	UserID INT NOT NULL IDENTITY(100,1) PRIMARY KEY,
	SchoolEmail VARCHAR(40) NOT NULL,
	Passwrd VARCHAR(40) NOT NULL
);

CREATE TABLE PAYMENT_OPTION (
	PaymentOptID INT NOT NULL PRIMARY KEY,
	PaymentType VARCHAR(40) NOT NULL
);

CREATE TABLE PRODUCT_CATEGORY (
	CategoryID INT NOT NULL PRIMARY KEY,
	CategoryName VARCHAR(40) NOT NULL
);

CREATE TABLE PRODUCT (
	ProductID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	ProductName VARCHAR(40) NOT NULL,
	ProdDescription VARCHAR(40) NOT NULL,
	CategoryID INT NOT NULL REFERENCES PRODUCT_CATEGORY(CategoryID)
);

CREATE TABLE USER_REVIEW (
	ReviewID INT NOT NULL IDENTITY(10000,1) PRIMARY KEY,
	Rating DECIMAL(2,1) NOT NULL CHECK (Rating >= 0 AND Rating <= 5),
	Comment VARCHAR(255) NULL,
	UserID INT NOT NULL REFERENCES WEB_USERS(UserID)
);

CREATE TABLE USER_CONTACT (
	ContactID INT NOT NULL IDENTITY(100,1) PRIMARY KEY,
	LastName VARCHAR(40) NOT NULL,
	FirstName VARCHAR(40) NOT NULL,
	StrAddress VARCHAR(255) NOT NULL,
	City VARCHAR(40) NOT NULL,
	UserState VARCHAR(2) NOT NULL,
	ZipCode VARCHAR(10) NOT NULL,
	Email VARCHAR(40) NOT NULL,
	Phone VARCHAR(12) NOT NULL,
	UserID INT NOT NULL REFERENCES WEB_USERS(UserID)
);

 CREATE TABLE PAYMENTS (
	PaymentID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	CreditCardNum VARCHAR(20) NOT NULL,
	ExpDate DATE NOT NULL,
	UserID INT NOT NULL REFERENCES WEB_USERS(UserID),
	PaymentOptID INT NOT NULL REFERENCES PAYMENT_OPTION(PaymentOptID)
);

CREATE TABLE SHOPPING_CART (
	ShoppingCartID INT NOT NULL IDENTITY(10000,1) PRIMARY KEY,
	UserID INT NOT NULL REFERENCES WEB_USERS(UserID)
);

CREATE TABLE PRODUCT_ITEM (
	ProductItemID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	Price DECIMAL(10,2) NOT NULL,
	Quantity INT NOT NULL,
	ItemImage IMAGE NOT NULL,
	Condition VARCHAR(40) NOT NULL,
	Size VARCHAR(10) NOT NULL,
	Color VARCHAR(10) NOT NULL
);

CREATE TABLE SHOPPING_CART_ITEM (
	ShoppingCartItemID INT NOT NULL IDENTITY(1000,1) PRIMARY KEY,
	Quantity INT NOT NULL,
	CardID INT NOT NULL REFERENCES SHOPPING_CART(ShoppingCartID),
	ProductItemID INT NOT NULL REFERENCES PRODUCT_ITEM(ProductItemID)
);